accessing
throwExceptionForResponseCode: aNumber
	
	(self errorDictionary at: aNumber) fork